namespace: dandyrow
name: stow
version: 0.2.0
readme: README.md
authors:
- Daniel Lowry <development@daniellowry.co.uk>
description: Ansible module to interact with GNU stow utility
license:
- GPL-3.0-only
tags:
  - linux
  - stow
  - gnu
dependencies: {}
repository: https://github.com/dandyrow/ansible-collection-stow
issues: https://github.com/dandyrow/ansible-collection-stow/issues
build_ignore:
  - output
  - __pycache__
  - '*_cache'
  - .coverage
  - .pylintrc
  - .git*
