---
name: Release
on:
  push:
    tags:
      - "*"
defaults:
  run:
    working-directory: ansible_collections/dandyrow/stow
jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source
        uses: actions/checkout@v3
        with:
          path: ansible_collections/dandyrow/stow
      - name: Set up Python 3
        uses: actions/setup-python@v3
        with:
          python-version: '3.10'
      - name: Install dependencies
        run: pip3 install ansible-core
      - name: Build collection tarball
        run: ansible-galaxy collection build
      - name: Release collection on Ansible Galaxy
        run: ansible-galaxy collection publish --token ${{ secrets.GALAXY_API_KEY }} -v dandyrow-stow-${{ github.ref_name }}.tar.gz
