---
name: Tests
on: push
jobs:
  sanity:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python 3
        uses: actions/setup-python@v3
        with:
          python-version: '3.10'
      - name: Install dependencies
        run: apt install ansible-core
      - name: Run sanity tests
        run: ansible-test sanity --docker default -v
  unit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python 3
        uses: actions/setup-python@v3
        with:
          python-version: '3.10'
      - name: Install dependencies
        run: apt install ansible-core
      - name: Run sanity tests
        run: ansible-test unit --docker default -v
